properties([parameters([booleanParam(defaultValue: false, description: '', name: 'isRelease')])])

node("dockerhost1") {

    stage("checkout") {
        checkout scm
    } 
       
    stage("build") {
        docker.image("praqma/pac").inside() {
            sh 'rake'
        }
    }

    stage("changelog") {
        pac()
    }

    stage("release") {
        def version = readFile("version.properties").split("=")[1].trim()
        def releaseTag = "$version-${env.BUILD_NUMBER}"
        echo "Potential release candidate is: $releaseTag"
        if(params?.isRelease) {
            echo "Building release"
        } else {
            echo "Not building release"
        }
    }
    
}