:general:
  :strict: false
 
:templates:
  - { location: templates/default_id_report.md, output: ids.md }
  - { location: templates/default.md, output: default.md }
  - { location: templates/default_html.html, pdf: true, output: default.html }

:task_systems:
  - 
    :name: none
    :regex:
      - { pattern: '/Issue:\s*(\d+)/i', label: none }
      - { pattern: '/Issue:\s*(none)/i', label: none }
      - { pattern: '/(#\d+)/', label: none }
      - { pattern: '/us:(\d+)/', label: none }
    :delimiter: '/,|\s/'
  -
    :name: jira
    :query_string: "http://your.server.hostname/rest/api/latest/issue/#{task_id}"
    :usr: "user"  
    :pw: "password"
    :regex:
    - { pattern: '/(PRJ-\d+)/i', label: jira }      
  -
    :name: trac
    :trac_url: "https://my.trac.site"
    :trac_usr: "user"
    :trac_pwd: "pass"
    :regex:
    - { pattern: '/Ticket-(\d+)/i', label: trac }  
  
:vcs:
  :type: git
  :usr:
  :pwd:
  :repo_location: '.'
  :release_regex: 'tags'
