:general:
  :strict: false
 
:templates:
  - { location: templates/default_html.html }

:task_systems:
  -
    :name: none
    :query_string: "https://api.github.com/repos/Praqma/Praqmatic-Automated-Changelog/issues/#{task_id}"
    :usr:
    :pw: 
    :regex:
    - { pattern: '/#(\d+)/i', label: github }      
  
:vcs:
  :type: git
  :filter_paths:
    - 'lib/'