:general:
  :strict: false
 
:templates:
  - { location: /data/templates/examples/github.html, output: default-generated.html }

:task_systems:
  -
    :name: json
    :query_string: "https://api.github.com/repos/Praqma/Praqmatic-Automated-Changelog/issues/#{task_id}"
    :regex:
    - { pattern: '/#(\d+)/i', label: github }      
  
:vcs:
  :type: git
  :repo_location: '.'