:general:
  date_template: '%Y-%m-%d'
  :strict: false
 
:templates:
  - { location: /data/templates/examples/github.html, pdf: false, output: default-generated.html }

:task_systems:
  -
    :regex:
    - { pattern: '/#(\d+)/i', label: github }        
    :name: jira
    :steps:
      - 
        :query: "https://api.github.com/repos/Praqma/Praqmatic-Automated-Changelog/issues/#{task_id}"
        :usr: 
        :pw:
        :namespace: github
  
:vcs:
  :type: git
  :repo_location: '.'