:general:
  :strict: false
  #:ssl_verify: false

:templates:
  - { location: templates/examples/github.html, output: 'reports/github-report.html'}

:task_systems:
  -
    <% res = Netrc.read(/data/.netrc) %>
    <% net_rc_username = res[:user] %>  
    :dummy: <%= net_rc_username %>
    :name: json
    :regex:
      - { pattern: '/#(\d+)/', label: github }
    :query_string: "https://api.github.com/repos/Praqma/Praqmatic-Automated-Changelog/issues/#{task_id}"
    :auth:
      :github:
        :token: <%= ENV['GITHUB_API_TOKEN'] %> # ""
        :headers:
          Content-Type: "application/json"
   #:auth:
   #  :basic:
   #    :username: "ENV['BASIC_USERNAME']"
   #    :password: "ENV['BASIC_PW']" 
   #:auth:
   #  :basic:
   #    :netrc_file: "ENV['BASIC_USERNAME']"

  
:vcs:
  :repo_location: '.'
