:general:
  :strict: false
 
:templates:
  - { location: templates/default.md }
  - { location: templates/default_html.html }

:task_systems:
  - 
    :name: none
    :regex:
      - { pattern: '/Issue:\s*(\d+)/i', label: none }
      - { pattern: '/Issue:\s*(none)/i', label: none }
      - { pattern: '/(#\d+)/', label: none }
      - { pattern: '/us:(\d+)/', label: none }
    :delimiter: '/,|\s/'
  -
    :name: jira
    :query_string: "http://your.server.hostname/rest/api/latest/issue/#{task_id}"
    :usr: "user"  
    :pw: "password"
    :regex:
    - { pattern: '/(PRJ-\d+)/i', label: jira }        
  
:vcs:
  :type: git
