:general:
  :strict: false
  #:ssl_verify: false

:templates:
  - { location: templates/examples/github.html, output: 'reports/github-report.html'}

:task_systems:
  -
    :name: json
    :regex:
      - { pattern: '/#(\d+)/', label: github }
    :query_string: "https://api.github.com/repos/Praqma/Praqmatic-Automated-Changelog/issues/#{task_id}"
    :auth:
      :github:
        :token: "ENV['GITHUB_API_TOKEN']"
   #:auth:
   #  :basic:
   #    :username: "ENV['BASIC_USERNAME']"
   #    :password: "ENV['BASIC_PW']" 
  
:vcs:
  :type: git
  :repo_location: '.'
