:general:
  :strict: true

:templates:
  - { location: /usr/src/app/templates/default_id_report.md, output: ids.md }

:task_systems:
  -
    :name: none
    :regex:
      - { pattern: '/(#\d+)/', label: none }
:vcs:
  :type: git
  :repo_location: '.'
