general:
  strict: true

templates:
  - { location: templates/default.md, output: default.md }
  - { location: templates/default.html, pdf: true, output: default.html }

task_systems:
  -
    name: none
    regex:
      - { pattern: '(#\d+)'}
vcs:
  repo: "."
  token: ""
